name: Daily Selenium Run

on:
  schedule:
    - cron: '0 11 * * 1-5'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    env:
      STATPRO_USERNAME: ${{ secrets.STATPRO_USERNAME }}
      STATPRO_PASSWORD: ${{ secrets.STATPRO_PASSWORD }}
      SFTP_HOSTNAME: ${{ secrets.SFTP_HOSTNAME }}
      SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
      SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      REMOTE_FOLDER: ${{ secrets.REMOTE_FOLDER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install selenium
        pip install webdriver_manager
        pip install openpyxl
        pip install paramiko

    - name: Run Selenium script
      run: python auto_download.py

    - name: Commit and push changes
      run: |
        git config --global user.email "bnguyen@tidalfg.com"
        git config --global user.name "brettnguyenTidal"
        git add .
        git commit -m "Update exported files"
        git push

